name: Deployment Win

on: 
  push:
    tags:
      - v*
      - w*

jobs:
  release-windows:
    env:
      REPOSITORY_NAME: SanityController
      BUILD_DIRECTORY: cmake-build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      shell: bash
      run: |
        cmake -B ${BUILD_DIRECTORY}
        cmake --build ${BUILD_DIRECTORY} --target ${REPOSITORY_NAME}_All -j 2 --config Release

    - name: Packaging Files
      shell: bash
      run: |
        chmod 755 bin/packaging_win.sh
        ./bin/packaging_win.sh "${BUILD_DIRECTORY}/${REPOSITORY_NAME}_artefacts/Release" "${REPOSITORY_NAME}"

    - name: Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: pkg/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
